src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finished</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test_Case__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preconditions__c</fullName>
        <label>Preconditions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Test Cases</relationshipLabel>
        <relationshipName>Test_Cases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_story__c</fullName>
        <description>URL field that works as link to the user story which this test case is related to.</description>
        <label>User story</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Test Case</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Test Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UpdateContactAddressesTest.cls
@isTest
private class UpdateContactAddressesTest {
    @testSetup
    static void setup() {
			Project__c a= new Project__c(Name='TEST CC',Status__c = 'Ongoing');
			insert a;
			for(Integer i = 0; i < 5; i++){
				Test_Case__c tc= new Test_Case__c(Title__c='TEST'+i ,Preconditions__c='NOTHING',Description__c='Description',User_story__c = 'www.someuserstorie.com',Project__c=a.Id);
				insert tc;
			}
    }

    static testmethod void test() {
        Test.startTest();
        OngoingProjects op = new OngoingProjects();
        Id batchId = Database.executeBatch(op);
        Test.stopTest();
        // after the testing stops, assert records were updated properly
        System.assertEquals(1, [SELECT COUNT() FROM AsyncApexJob WHERE ID = :batchId ]);
    }

}