src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finished</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test_Case__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preconditions__c</fullName>
        <label>Preconditions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Test Cases</relationshipLabel>
        <relationshipName>Test_Cases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_story__c</fullName>
        <description>URL field that works as link to the user story which this test case is related to.</description>
        <label>User story</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Test Case</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Test Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Testcase_Step__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expected_result__c</fullName>
        <label>Expected result</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test_Case__c</fullName>
        <label>Test Case</label>
        <referenceTo>Test_Case__c</referenceTo>
        <relationshipLabel>Testcase Steps</relationshipLabel>
        <relationshipName>Testcase_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Testcase Step</label>
    <nameField>
        <displayFormat>TS-{000000000}</displayFormat>
        <label>Testcase Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Testcase Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/testClass.cls
@isTest
private class testClass {

	@isTest static void test_method_getProjects() {
		Project__c a= new Project__c(Name='TEST',Status__c = 'Ongoing');
		insert a;
		for(Integer i = 0; i < 5; i++){
			Test_Case__c tc= new Test_Case__c(Title__c='TEST'+i ,Preconditions__c='NOTHING',Description__c='Description',User_story__c = 'www.someuserstorie.com',Project__c=a.Id);
			insert tc;
		}
		System.assertEquals(1,ProjectController.getProjects().size());
		// Implement test code System.assertEquals()
	}

	@isTest static void test_method_deleteTestCase() {
		Project__c p= new Project__c(Name='TEST1',Status__c = 'Ongoing');
		insert p;
		for(Integer i = 0; i < 5; i++){
			Test_Case__c tc= new Test_Case__c(Title__c='TEST'+i ,Preconditions__c='NOTHING',Description__c='Description',User_story__c = 'www.someuserstorie.com',Project__c=p.Id);
			insert tc;
		}
		List<Test_Case__c> a = [Select Id from Test_Case__c where Title__c = 'TEST0'];

		ProjectController.deleteTestCase(a[0]);
		List<Test_Case__c> listtc =[Select Id from Test_Case__c];
		System.assertEquals(4,listtc.size());

		// Implement test code
	}

	@isTest static void test_method_upsertTestCase() {
		Project__c p= new Project__c(Name='TEST1',Status__c = 'Ongoing');
		insert p;
		for(Integer i = 0; i < 5; i++){
			Test_Case__c tc= new Test_Case__c(Title__c='TEST'+i ,Preconditions__c='NOTHING',Description__c='Description',User_story__c = 'www.someuserstorie.com',Project__c=p.Id);
			insert tc;
		}
		List<Test_Case__c> a = [Select Id from Test_Case__c where Title__c = 'TEST0'];
		a[0].Title__c='A';
		a[0].Preconditions__c='A';
		a[0].Description__c='A';
		a[0].User_story__c='as.as.as';

		ProjectController.upsertTestCase(a[0]);
		List<Test_Case__c> listtc =[Select Id from Test_Case__c where Title__c= 'A' AND Description__c='A' and User_story__c='as.as.as'];
		System.assertEquals(1,listtc.size());

		// Implement test code
	}
	@isTest static void test_method_getSteps() {
		Project__c p= new Project__c(Name='TEST1',Status__c = 'Ongoing');
		insert p;
		Test_Case__c tc= new Test_Case__c(Title__c='TEST' ,Preconditions__c='NOTHING',Description__c='Description',User_story__c = 'www.someuserstorie.com',Project__c=p.Id);
			insert tc;
			List<Testcase_Step__c> tcs=new List<Testcase_Step__c> ();
			for(Integer j = 0; j < 5; j++){
				Testcase_Step__c tcss= new Testcase_Step__c(Description__c='Description'+j, Expected_result__c	 = 'good',Test_Case__c= tc.Id);
				tcs.add(tcss);
			}
			insert tcs;

		List<Test_Case__c> testcase = [Select Id from Test_Case__c where Title__c = 'TEST'];
		String recordId=testcase[0].Id;
		List<Testcase_Step__c>listtcs=ProjectController.getSteps(recordId);
		System.assertEquals(5,listtcs.size());

		// Implement test code
	}
	@isTest static void test_method_getOrder(){
		Project__c p= new Project__c(Name='TEST1',Status__c = 'Ongoing');
		insert p;
		Test_Case__c tc= new Test_Case__c(Title__c='TEST' ,order_step__c='a,b,c,1,2,3,4,5',Preconditions__c='NOTHING',Description__c='Description',User_story__c = 'www.someuserstorie.com',Project__c=p.Id);
		insert tc;
		System.assertEquals('a,b,c,1,2,3,4,5',ProjectController.getOrder(tc.Id));

	}
	@isTest static void test_method_setStepOrder(){
		Project__c p= new Project__c(Name='TEST1',Status__c = 'Ongoing');
		insert p;
		Test_Case__c tc= new Test_Case__c(Title__c='TEST' ,order_step__c='',Preconditions__c='NOTHING',Description__c='Description',User_story__c = 'www.someuserstorie.com',Project__c=p.Id);
		insert tc;
		ProjectController.setStepOrder(tc.Id,'a,b,c,1,2,3,4,5');
		System.assertEquals('a,b,c,1,2,3,4,5',ProjectController.getOrder(tc.Id));
	}






}